#docker version with different features accessible depending on the version
#useless deprecated
#version: '3.8'

services:
  angular-app:
    image : mcr.microsoft.com/dotnet/aspnet:latest
    #use the docker file in the current dir to build the image
    build: .
    ports:
    #the first is the port use in the actual machine
    #the second 4200 is the port use in the container
      - "4200:4200"
    volumes:
    ##mount the current directory into app inside the contaienr
      - .:/app
    #be sure that the mcr.microsoft.com/dotnet is used
    # in order to avoid conflicts
      - /app/mcr.microsoft.com/dotnet/sdk